export type PortfolioItem = {
  id: string;
  title: string;
  subtitle: string;
  categories: string[];
  year: string;
  mainImage: {
    src: string;
    width: number;
    height: number;
    hint: string;
  };
  description: string;
  link?: {
    url: string;
    name: string;
  };
  gallery: {
    src: string;
    width: number;
    height: number;
    hint: string;
  }[];
};

export const portfolioCategories = ["Todos", "Branding", "Diseño Gráfico", "Diseño App", "Diseño Web", "Logo", "Packaging", "Publicitario", "Editorial", "Ilustración"];

export const portfolioData: PortfolioItem[] = [
  {
    id: "audio-devices",
    title: "Audio Devices",
    subtitle: "Ilustración",
    categories: ["Ilustración"],
    year: "2024",
    mainImage: {
      src: "/images/portfolio/audio-devices/aud-00.jpg",
      width: 1600,
      height: 900,
      hint: "cover",
    },
    description: "'Audio Devices' es una colección de ilustraciones hiperrealistas centrada en amplificadores de audio vintage. Cada pieza ha sido creada meticulosamente en Figma, destacando los detalles y la estética clásica de estos icónicos equipos de sonido. El proyecto es un homenaje visual a la ingeniería y el diseño de la época dorada del audio.",
    gallery: [
      {
      src: "/images/portfolio/audio-devices/aud-01.jpg",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
      {
      src: "/images/portfolio/audio-devices/aud-02.jpg",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
      {
      src: "/images/portfolio/audio-devices/aud-03.jpg",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
      {
      src: "/images/portfolio/audio-devices/aud-04.jpg",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
      {
      src: "/images/portfolio/audio-devices/aud-05.jpg",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
    ],
  },
  {
    id: "cristina-y-pablo",
    title: "Cristina & Pablo",
    subtitle: "Diseño Gráfico",
    categories: ["Diseño Gráfico"],
    year: "2023",
    mainImage: {
      src: "/images/portfolio/cristina-y-pablo/cyp-00.jpg",
      width: 1600,
      height: 900,
      hint: "cover",
    },
    description: "El proyecto para la boda de Cristina y Pablo consistió en el diseño de una identidad visual completa y unificada. El elemento central del diseño es una fotografía de la pared de la iglesia donde se celebró la ceremonia, utilizada como fondo, así como detalles extraídos del forjado, para crear una atmósfera personal y coherente en todas las piezas gráficas. Para la comunicación se emplearon dos estilos tipográficos: una fuente manuscrita animada para el 'Save the Date', que aporta un toque personal y dinámico, y una tipografía serif para el resto de textos. Además, se desarrolló una landing page que centralizaba toda la información útil para los invitados, como direcciones y un formulario de confirmación, completando así una experiencia de usuario cuidada y funcional.",
    gallery: [
      {
      src: "/images/portfolio/cristina-y-pablo/cyp-01.gif",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
      {
      src: "/images/portfolio/cristina-y-pablo/cyp-01.jpg",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
    ],
  },
  {
    id: "kensa",
    title: "Kensa",
    subtitle: "Folleto",
    categories: ["Diseño Gráfico", "Editorial"],
    year: "2022",
    mainImage: {
      src: "/images/portfolio/kensa/ken-00.jpg",
      width: 1600,
      height: 900,
      hint: "cover",
    },
    description: "'Kensa' es un proyecto de diseño editorial que aborda la ciclicidad femenina a través de un folleto informativo. El diseño está concebido para educar y empoderar, presentando las fases del ciclo menstrual de una manera clara, accesible y visualmente atractiva. El objetivo es normalizar la conversación sobre la salud femenina y proporcionar una herramienta para el autoconocimiento, utilizando un lenguaje gráfico cuidado y respetuoso.",
    gallery: [
      {
      src: "/images/portfolio/kensa/ken-01.jpg",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
      {
      src: "/images/portfolio/kensa/ken-02.jpg",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
      {
      src: "/images/portfolio/kensa/ken-03.jpg",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
      {
      src: "/images/portfolio/kensa/ken-04.jpg",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
      {
      src: "/images/portfolio/kensa/ken-05.jpg",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
    ],
  },
  {
    id: "peaberry",
    title: "Peaberry",
    subtitle: "Branding",
    categories: ["Logo", "Branding"],
    year: "2022",
    mainImage: {
      src: "/images/portfolio/peaberry/pea-00.jpg",
      width: 1600,
      height: 900,
      hint: "cover",
    },
    description: "Peaberry es un proyecto de identidad de marca desarrollado para una cafetería especializada en almuerzos saludables. El concepto visual se inspira en el origen del café: el logotipo es una abstracción de la sección de una baya de peaberry, y la paleta de colores utiliza tonos marrones y verdes que evocan el grano antes de su tueste. La identidad se aplicó a diversos elementos, incluyendo una señalética interior y exterior fabricada en madera para aportar un toque orgánico y cálido. El resultado es una marca que trata de comunicar sus valores de naturalidad, salud y calidad.",
    gallery: [
      {
      src: "/images/portfolio/peaberry/pea-01.jpg",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
      {
      src: "/images/portfolio/peaberry/pea-02.jpg",
        width: 1600,
        height: 1600,
        hint: "mockup slide",
      },
      {
      src: "/images/portfolio/peaberry/pea-03.jpg",
        width: 1600,
        height: 1600,
        hint: "mockup slide",
      },
      {
      src: "/images/portfolio/peaberry/pea-04.jpg",
        width: 1600,
        height: 1600,
        hint: "mockup slide",
      },
    ],
  },
  {
    id: "watchdrop",
    title: "Watchdrop",
    subtitle: "Presentación",
    categories: ["Diseño Gráfico"],
    year: "2021",
    mainImage: {
      src: "/images/portfolio/watchdrop/wat-00.jpg",
      width: 1600,
      height: 900,
      hint: "cover",
    },
    description: "Presentación web para la casa de subastas de relojes 'Watchdrop'.",
    link: {
      url: "/content/portfolio/watchdrop/index.html",
      name: "Ver presentación"
    },
    gallery: [
      {
      src: "/images/portfolio/watchdrop/wat-01.gif",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
      {
      src: "/images/portfolio/watchdrop/wat-01.jpg",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
      {
      src: "/images/portfolio/watchdrop/wat-02.jpg",
        width: 1600,
        height: 1600,
        hint: "mockup slide",
      },
    ],
  },
  {
    id: "komo",
    title: "Komo",
    subtitle: "Branding & Diseño App",
    categories: ["Diseño Gráfico", "Branding", "Diseño App"],
    year: "2020",
    mainImage: {
      src: "/images/portfolio/komo/kom-00.jpg",
      width: 1600,
      height: 900,
      hint: "cover",
    },
    description: "Diseño de UI/UX para una app de compraventa de productos naturales de 'kilómetro 0'. El objetivo de la app es conectar directamente a consumidores con productores locales, fomentando el comercio justo y la alimentación sostenible. El diseño se enfoca en una experiencia de usuario intuitiva y fluida, que permite a los usuarios explorar productores cercanos, descubrir productos de temporada y realizar compras de forma segura y sencilla. La interfaz visual es limpia y orgánica, buscando transmitir los valores de frescura, confianza y comunidad que definen al proyecto.",
    gallery: [
      {
      src: "/images/portfolio/komo/kom-01.jpg",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
      {
      src: "/images/portfolio/komo/kom-02.jpg",
        width: 1600,
        height: 1600,
        hint: "mockup slide",
      },
    ],
  },
  {
    id: "cicma",
    title: "Cicma",
    subtitle: "Branding & Diseño Web",
    categories: ["Diseño Gráfico", "Branding", "Diseño Web"],
    year: "2020",
    mainImage: {
      src: "/images/portfolio/cicma/cic-00.jpg",
      width: 1600,
      height: 900,
      hint: "cover",
    },
    description: "Desarrollo de identidad de marca integral para 'Cicma', un centro especializado en cirugía de mano. El núcleo de la identidad es un logotipo conceptual de estilo lineal: una mano donde la palma está formada por la letra 'C', y el dedo corazón representa un láser quirúrgico, simbolizando la precisión y la tecnología avanzada del centro. El trabajo abarcó desde la identidad visual y la papelería corporativa hasta el diseño de la página web. En el entorno digital, se utilizó una mano animada como fondo para aportar una sensación de calidez, cercanía y cuidado. Además, se diseñó un conjunto de iconos personalizados para mantener la coherencia visual en todas las plataformas. El resultado es una marca que comunica profesionalidad, innovación y un enfoque centrado en el paciente.",
    link: {
      url: "/content/portfolio/watchdrop/index.html",
      name: "Ver presentación"
    },
    gallery: [
      {
      src: "/images/portfolio/cicma/cic-01.jpg",
        width: 1600,
        height: 1600,
        hint: "image slide",
      },
      {
      src: "/images/portfolio/cicma/cic-02.jpg",
        width: 1600,
        height: 1600,
        hint: "mockup slide",
      },
      {
      src: "/images/portfolio/cicma/cic-03.jpg",
        width: 1600,
        height: 1600,
        hint: "mockup slide",
      },
    ],
  },
  {
    id: "ivirma-global-education",
    title: "IVIRMA Global Education",
    subtitle: "Diseño Gráfico",
    categories: ["Diseño Gráfico", "Diseño Web"],
    year: "2019",
    mainImage: {
      src: "/images/portfolio/ivirma/ivi-00.jpg",
      width: 1600,
      height: 900,
      hint: "corporate bus",
    },
    description: "Durante mi trayectoria de cuatro años en IVIRMA Global Education, asumí un rol de diseñador multidisciplinar, encargado de la comunicación visual de la marca a través de múltiples plataformas. Mis responsabilidades abarcaron un amplio espectro de proyectos, desde el diseño de materiales corporativos y de marketing hasta el desarrollo de soluciones digitales. En el ámbito digital, lideré el diseño y la conceptualización de páginas web, incluyendo repositorios de vídeo y plataformas de comformación, así como el desarrollo de web apps. Mi rol también tuvo un fuerte componente audiovisual, encargándome del ciclo completo de producción de vídeo: desde el montaje y la edición hasta el diseño de portadas y la creación de animaciones. Esta posición me permitió desarrollar una visión integral de la comunicación de marca, asegurando la coherencia y calidad en todos los puntos de contacto",
    gallery: [
      {
      src: "/images/portfolio/ivirma/ivi-01.gif",
        width: 1920,
        height: 1200,
        hint: "mascot ad screenshot",
      },
      {
      src: "/images/portfolio/ivirma/ivi-01.jpg",
        width: 1556,
        height: 992,
        hint: "mascot ad screenshot",
      },
      {
      src: "/images/portfolio/ivirma/ivi-02.jpg",
        width: 1640,
        height: 620,
        hint: "facebook cover",
      },
      {
      src: "/images/portfolio/ivirma/ivi-03.gif",
        width: 1556,
        height: 992,
        hint: "stationery mockup",
      },
      {
      src: "/images/portfolio/ivirma/ivi-04.jpg",
        width: 1556,
        height: 992,
        hint: "stationery mockup",
      },
      {
      src: "/images/portfolio/ivirma/ivi-05.jpg",
        width: 1556,
        height: 992,
        hint: "stationery mockup",
      },
      {
      src: "/images/portfolio/ivirma/ivi-06.jpg",
        width: 1556,
        height: 992,
        hint: "stationery mockup",
      },
      {
      src: "/images/portfolio/ivirma/ivi-07.jpg",
        width: 1556,
        height: 992,
        hint: "stationery mockup",
      },
      {
      src: "/images/portfolio/ivirma/ivi-08.jpg",
        width: 1556,
        height: 992,
        hint: "stationery mockup",
      },
      {
      src: "/images/portfolio/ivirma/ivi-09.jpg",
        width: 1556,
        height: 992,
        hint: "stationery mockup",
      },
      {
      src: "/images/portfolio/ivirma/ivi-10.jpg",
        width: 1556,
        height: 992,
        hint: "stationery mockup",
      },
    ],
  },
  {
    id: "maseuropa",
    title: "maseuropa",
    subtitle: "Branding",
    categories: ["Branding"],
    year: "2018",
    mainImage: {
      src: "/images/portfolio/maseuropa/mas-00.jpg",
      width: 1600,
      height: 900,
      hint: "corporate bus",
    },
    description: "En mi colaboración con maseuropa, participé activamente en la fase inicial de la empresa, desempeñando un rol fundamental en la construcción de su identidad visual. Mi trabajo consistió en desarrollar las aplicaciones de la marca en sus primeros pasos, estableciendo un sistema visual coherente para todos sus puntos de contacto. Además de definir la implementación de la marca, también me encargué del diseño y la ejecución de las campañas de marketing iniciales, contribuyendo de manera directa al lanzamiento y posicionamiento de la empresa en el mercado. Fue una oportunidad para dar forma a una marca desde sus cimientos y asegurar que su comunicación visual fuera sólida y efectiva desde el primer día.",
    gallery: [
      {
      src: "/images/portfolio/maseuropa/mas-01.jpg",
        width: 1556,
        height: 992,
        hint: "mascot ad screenshot",
      },
      {
      src: "/images/portfolio/maseuropa/mas-02.jpg",
        width: 1640,
        height: 620,
        hint: "facebook cover",
      },
      {
      src: "/images/portfolio/maseuropa/mas-03.jpg",
        width: 1556,
        height: 992,
        hint: "stationery mockup",
      },
    ],
  },
  {
    id: "beauty-luz",
    title: "Beauty Luz",
    subtitle: "Branding",
    categories: ["Logo", "Branding"],
    year: "2017",
    mainImage: {
      src: "/images/portfolio/beauty-luz/bea-00.jpg",
      width: 1556,
      height: 992,
      hint: "logo on corporate laser background",
    },
    description: "Proyecto de identidad corporativa para el centro de estética BeautyLUZ. Se desarrolló la marca y sus aplicaciones a diversas piezas, tanto gráficas (flyers) como de señalética y rotulación del local. Esto incluyó el diseño de vinilos para el escaparate, la banderola exterior y la persiana metálica.",
    gallery: [
      {
      src: "/images/portfolio/beauty-luz/bea-01.jpg",
        width: 1556,
        height: 992,
        hint: "services flyer",
      },
    ],
  },
  {
    id: "tamara-falco-preysler",
    title: "Tamara Falcó Preysler",
    subtitle: "Logo",
    categories: ["Logo"],
    year: "2017",
    mainImage: {
      src: "/images/portfolio/tamara-falco-preysler/tfp-00.jpg",
      width: 1600,
      height: 900,
      hint: "logo on corporate laser background",
    },
    description: "Diseño de un logotipo para la colección de ropa de Tamara Falcó Preysler. El objetivo principal era crear una marca que reflejara la elegancia y el estilo personal que la colección caracterizan, utilizando sus iniciales 'TFP'. El resultado es un monograma sofisticado y limpio que entrelaza las tres letras de forma equilibrada y armónica. El diseño funciona como una firma de autor, aportando un sello de distinción y calidad a las prendas de la colección. La marca logra ser atemporal y reconocible, encapsulando la esencia de un proyecto de moda personal y exclusivo",
    gallery: [
      {
      src: "/images/portfolio/tamara-falco-preysler/tfp-01.jpg",
        width: 1600,
        height: 900,
        hint: "services flyer",
      },
      {
      src: "/images/portfolio/tamara-falco-preysler/tfp-02.jpg",
        width: 1600,
        height: 900,
        hint: "services flyer",
      },
    ],
  },
  {
    id: "unas-vacaciones",
    title: "Unas Vacaciones de la Ciudad al Campo",
    subtitle: "Editorial",
    categories: ["Editorial"],
    year: "2016",
    mainImage: {
      src: "/images/portfolio/unas-vacaciones/una-00.jpg",
      width: 1556,
      height: 992,
      hint: "folder mockup",
    },
    description: "'Unas Vacaciones de la Ciudad al Campo' es un proyecto de diseño editorial con un profundo significado personal. Se trata de la maquetación del libro escrito por mi padre, Jorge Stuyck del Portillo, que narra sus recuerdos de infancia. El libro nació de un proceso de superación personal, ya que fue escrito como parte de su rehabilitación con una logopeda tras sufrir un ictus. Mi labor consistió en diseñar y estructurar el libro, integrando sus textos con las ilustraciones originales creadas por él mismo. El objetivo fue crear una composición limpia y cálida que arropara la historia, respetando su sensibilidad y poniendo en valor tanto la narrativa como el arte. El resultado es un homenaje a la memoria, la superación y la creatividad, un proyecto que trasciende el diseño para convertirse en un legado familiar.",
    gallery: [
      {
        src: "/images/portfolio/unas-vacaciones/una-01.jpg",
        width: 1556,
        height: 992,
        hint: "folder mockup open",
      },
      {
        src: "/images/portfolio/unas-vacaciones/una-02.jpg",
        width: 1556,
        height: 992,
        hint: "coaster mockup",
      },
    ],
  },
  {
    id: "centro-porsche-valencia",
    title: "Centro Porsche Valencia",
    subtitle: "Diseño Gráfico",
    categories: ["Diseño Gráfico"],
    year: "2016",
    mainImage: {
      src: "/images/portfolio/porsche-valencia/por-00.jpg",
      width: 1556,
      height: 992,
      hint: "folder mockup",
    },
    description: "Diseño de carpeta de bienvenida y satisfacción post-venta, siguiendo estrictamente las directrices de la identidad visual de Porsche para entregar documentación de forma exclusiva. También diseñé e instalé las firmas de correo electrónico corporativas para todo el equipo, asegurando una comunicación de marca coherente y profesional en todos los puntos de contacto con el cliente.",
    gallery: [
      {
        src: "/images/portfolio/porsche-valencia/por-01.jpg",
        width: 1556,
        height: 992,
        hint: "folder mockup open",
      },
      {
        src: "/images/portfolio/porsche-valencia/por-02.jpg",
        width: 1556,
        height: 992,
        hint: "coaster mockup",
      },
    ],
  },
  {
    id: "shoot-the-twin",
    title: "Shoot The Twin",
    subtitle: "Logo",
    categories: ["Logo"],
    year: "2016",
    mainImage: {
      src: "/images/portfolio/shoot-the-twin/sho-00.jpg",
      width: 1556,
      height: 992,
      hint: "jacket",
    },
    description: "Diseño de logotipo que contrasta un estilo retro con uno minimalista. La identidad principal se presenta en un logotipo de emblema circular con una tipografía de inspiración Art Déco, que le otorga una estética vintage y elaborada. A partir de este, se extrae un isotipo secundario, una abstracción minimalista que reduce el logo a sus elementos esenciales —un círculo y dos líneas, 'shoot the twin'—, creando una figura icónica y memorable que evoca a una persona. Esta versátil identidad visual funciona tanto en un sobrio blanco y negro como en una paleta de colores más moderna y suave, con tonos pastel como el verde menta y el lila.",
    gallery: [
      {
      src: "/images/portfolio/shoot-the-twin/sho-01.jpg",
        width: 1556,
        height: 992,
        hint: "negative logo on dark background",
      },
      {
      src: "/images/portfolio/shoot-the-twin/sho-02.jpg",
        width: 1556,
        height: 992,
        hint: "color variation favicon",
      },
      {
      src: "/images/portfolio/shoot-the-twin/sho-03.jpg",
        width: 1556,
        height: 992,
        hint: "baseball t-shirt",
      },
      {
      src: "/images/portfolio/shoot-the-twin/sho-04.jpg",
        width: 1556,
        height: 992,
        hint: "cap",
      },
      {
      src: "/images/portfolio/shoot-the-twin/sho-05.jpg",
        width: 1556,
        height: 992,
        hint: "t-shirt tag mockup",
      },
      {
      src: "/images/portfolio/shoot-the-twin/sho-06.jpg",
        width: 1556,
        height: 992,
        hint: "polo",
      },
    ],
  },
  {
    id: "ayuda-a-la-ciencia",
    title: "Ayuda a la Ciencia",
    subtitle: "Branding & UI/UX",
    categories: ["Logo", "Branding", "Diseño Web"],
    year: "2016",
    mainImage: {
      src: "/images/portfolio/ayuda-a-la-ciencia/aci-00.jpg",
      width: 1556,
      height: 992,
      hint: "logo on website on ipad",
    },
    description: "Proyecto de branding y diseño web para 'Ayuda a la Ciencia', una plataforma online dedicada a conectar a voluntarios con estudios científicos que necesitan participantes. El objetivo principal fue crear una experiencia de usuario intuitiva y amigable, con un portal accesible y claro. El trabajo abarcó desde la creación del logotipo y la identidad corporativa hasta el diseño de la interfaz de la página web.",
    gallery: [
      {
        src: "/images/portfolio/ayuda-a-la-ciencia/aci-01.jpg",
        width: 1556,
        height: 992,
        hint: "responsive website on multiple devices",
      },
      {
        src: "/images/portfolio/ayuda-a-la-ciencia/aci-02.jpg",
        width: 1556,
        height: 992,
        hint: "horizontal negative full logo on gradient background",
      },
      {
        src: "/images/portfolio/ayuda-a-la-ciencia/aci-03.jpg",
        width: 1556,
        height: 992,
        hint: "positive full logo",
      },
    ],
  },
  {
    id: "miguel-vizcaino",
    title: "Miguel Vizcaíno",
    subtitle: "Logo",
    categories: ["Logo"],
    year: "2015",
    mainImage: {
      src: "/images/portfolio/miguel-vizcaino/mig-00.jpg",
      width: 1556,
      height: 992,
      hint: "logo",
    },
    description: "Diseño de logotipo para el diseñador de moda Miguel Vizcaino, definido por un enfoque minimalista, geométrico y sofisticado, utilizando una tipografía de palo seco, muy fina y expandida, que aporta un carácter moderno y exclusivo. El sistema de marca incluye tanto el logotipo con el nombre completo como un monograma circular que fusiona las iniciales 'M' y 'V'. Al aplicarse sobre la fotografía de moda, de estilo que actúa como una firma sutil que complementa la dirección de arte sin restarle protagonismo a las prendas.",
    gallery: [
      {
      src: "/images/portfolio/miguel-vizcaino/mig-01.jpg",
        width: 1556,
        height: 992,
        hint: "logo construction",
      },
      {
      src: "/images/portfolio/miguel-vizcaino/mig-02.jpg",
        width: 1556,
        height: 992,
        hint: "line monogram",
      },
      {
      src: "/images/portfolio/miguel-vizcaino/mig-03.jpg",
        width: 1556,
        height: 992,
        hint: "monogram with logo",
      },
      {
      src: "/images/portfolio/miguel-vizcaino/mig-04.jpg",
        width: 1556,
        height: 992,
        hint: "billboard with logo and model",
      },
      {
      src: "/images/portfolio/miguel-vizcaino/mig-05.jpg",
        width: 1556,
        height: 992,
        hint: "billboard with logo and model",
      },
    ],
  },
  {
    id: "ruiz-de-la-prada-arquitectos",
    title: "Ruiz de la Prada Arquitectos",
    subtitle: "Branding",
    categories: ["Logo", "Branding"],
    year: "2015",
    mainImage: {
      src: "/images/portfolio/ruiz-de-la-prada-arquitectos/rdp-00.jpg",
      width: 1556,
      height: 992,
      hint: "logo",
    },
    description: "Desarrollo de identidad corporativa para el grupo Ruiz de la Prada, que integra sus tres áreas de negocio: Arquitectura, Construcción y Paisajismo. El diseño se articula en torno a un logotipo tipográfico con una estructura modular y de bloque, que evoca solidez y un carácter arquitectónico. La clave del sistema es un código de colores (magenta, gris y verde) que identifica y diferencia a cada una de las divisiones. La identidad, que incluye también un monograma para aplicaciones abreviadas, se aplica en piezas como tarjetas de visita transparentes que refuerzan la imagen de una empresa moderna e innovadora.",
    gallery: [
      {
      src: "/images/portfolio/ruiz-de-la-prada-arquitectos/rdp-01.jpg",
        width: 1556,
        height: 992,
        hint: "logo construction",
      },
      {
      src: "/images/portfolio/ruiz-de-la-prada-arquitectos/rdp-02.jpg",
        width: 1556,
        height: 992,
        hint: "line monogram",
      },
    ],
  },
  {
    id: "djembe",
    title: "Djembé",
    subtitle: "Logo",
    categories: ["Logo"],
    year: "2015",
    mainImage: {
      src: "/images/portfolio/djembe/dje-00.jpg",
      width: 1556,
      height: 992,
      hint: "logo on wooden wall",
    },
    description: "Diseño de logotipo para 'Djembe', un bar de playa con una marcada inspiración en la cultura surf y reggae. El objetivo era crear una identidad visual vibrante, relajada y memorable. El diseño se basa en una tipografía personalizada de estilo manual, que le aporta un carácter único y cercano. El logotipo se estructura en forma de emblema, utilizando la silueta de una tabla de surf como contenedor principal, lo que lo vincula directamente con el ambiente costero. La paleta de colores, inspirada en la bandera rasta, utiliza el rojo, verde y amarillo para transmitir una sensación de energía, naturaleza y buena vibra. El resultado es una marca con fuerte personalidad, perfectamente alineada con el espíritu de un bar de playa.",
    gallery: [
      {
      src: "/images/portfolio/djembe/dje-01.jpg",
        width: 1556,
        height: 992,
        hint: "logo construction",
      },
      {
      src: "/images/portfolio/djembe/dje-02.jpg",
        width: 1556,
        height: 992,
        hint: "logo on corporate background",
      },
    ],
  },
  {
    id: "nepher",
    title: "Nepher",
    subtitle: "Branding",
    categories: ["Logo", "Branding"],
    year: "2015",
    mainImage: {
      src: "/images/portfolio/nepher/nep-00.jpg",
      width: 1556,
      height: 992,
      hint: "logo on corporate background",
    },
    description: "Desarrollo de identidad de marca integral para Nepher, una empresa del sector de la belleza y el bienestar que opera bajo el lema 'Salud, Belleza & Armonía'. El concepto visual se inspira en la delicadeza, la transformación y la naturaleza, utilizando la metáfora del diente de león y una paleta de colores suaves y elegantes para transmitir calma y sofisticación. El logotipo, minimalista, junto con la identidad visual, se aplica de forma coherente a través de un amplio abanico de soportes, incluyendo tarjetas de visita, bonos de regalo, tarjetas de fidelización y papelería corporativa, construyendo una imagen de marca profesional, serena y cohesionada.",
    gallery: [
      {
      src: "/images/portfolio/nepher/nep-01.jpg",
        width: 1556,
        height: 992,
        hint: "secondary logo on corporate background",
      },
      {
      src: "/images/portfolio/nepher/nep-02.jpg",
        width: 1556,
        height: 992,
        hint: "negative logo on corporate background",
      },
      {
      src: "/images/portfolio/nepher/nep-03.jpg",
        width: 1556,
        height: 992,
        hint: "business cards mockup",
      },
      {
      src: "/images/portfolio/nepher/nep-04.jpg",
        width: 1556,
        height: 992,
        hint: "street sign logo mockup",
      },
      {
      src: "/images/portfolio/nepher/nep-05.jpg",
        width: 1556,
        height: 992,
        hint: "brochure mockup",
      },
      {
      src: "/images/portfolio/nepher/nep-06.jpg",
        width: 1556,
        height: 992,
        hint: "notepad mockup",
      },
      {
      src: "/images/portfolio/nepher/nep-07.jpg",
        width: 1556,
        height: 992,
        hint: "flyers mockup",
      },
    ],
  },
  {
    id: "cokecancook",
    title: "cokecancook",
    subtitle: "Branding Personal",
    categories: ["Logo", "Branding"],
    year: "2015",
    mainImage: {
      src: "/images/portfolio/cokecancook/cok-00.jpg",
      width: 1556,
      height: 992,
      hint: "horizontal negative logo mockup on stone wall",
    },
    description: "La identidad visual para 'cokecancook' (2015) nace de un juego de palabras: la sonoridad del nombre ('Coke can cook') se fusiona con el concepto de 'cocinar' ideas y diseños. Este principio se materializa en el logotipo, que utiliza una sartén y huevos fritos como elementos centrales para crear una imagen simpática y memorable. A partir de ahí, se desarrolló un sistema visual completo para uso digital e impreso, incluyendo tarjetas de visita, plantillas y recursos para redes sociales, logrando una marca coherente, con mucha personalidad y fácil de recordar.",
    gallery: [
      {
      src: "/images/portfolio/cokecancook/cok-01.jpg",
        width: 1556,
        height: 992,
        hint: "horizontal negative logo on striped dark background",
      },
      {
      src: "/images/portfolio/cokecancook/cok-02.jpg",
        width: 1556,
        height: 992,
        hint: "full logo on striped white background",
      },
      {
      src: "/images/portfolio/cokecancook/cok-03.jpg",
        width: 1556,
        height: 992,
        hint: "favicon on striped white background",
      },
      {
      src: "/images/portfolio/cokecancook/cok-04.jpg",
        width: 1556,
        height: 992,
        hint: "favicon pattern on dark background",
      },
    ],
  },
  {
    id: "atria-jobs",
    title: "Atria Jobs",
    subtitle: "Branding & UI/UX",
    categories: ["Logo", "Branding", "Diseño Web"],
    year: "2014",
    mainImage: {
      src: "/images/portfolio/atria-jobs/atr-00.jpg",
      width: 1333,
      height: 1333,
      hint: "favicon",
    },
    description: "Proyecto de identidad corporativa y diseño web para 'Atria', una consultora de recruitment internacional especializada en el sector sanitario y científico. El objetivo principal fue desarrollar una imagen de marca profesional y una plataforma online funcional para la captación de talento. El trabajo abarcó desde la creación del logotipo y la identidad visual hasta el diseño de la página web, plantillas para redes sociales y otros materiales corporativos.",
    gallery: [
      {
      src: "/images/portfolio/atria-jobs/atr-01.jpg",
        width: 1556,
        height: 992,
        hint: "negative sketch logo",
      },
      {
      src: "/images/portfolio/atria-jobs/atr-02.jpg",
        width: 1556,
        height: 992,
        hint: "favicon transparent over gradient background",
      },
      {
      src: "/images/portfolio/atria-jobs/atr-03.jpg",
        width: 1556,
        height: 992,
        hint: "responsive panel on multiple devices",
      },
    ],
  },
  {
    id: "siami",
    title: "Siami",
    subtitle: "Logo",
    categories: ["Logo"],
    year: "2014",
    mainImage: {
      src: "/images/portfolio/siami/sia-00.jpg",
      width: 1333,
      height: 1333,
      hint: "negative horizontal logo on dark background",
    },
    description: "Diseño de logotipo para Siami, una empresa especializada en sistemas audiovisuales. El concepto se centra en un isotipo, con formato de icono de aplicación, donde la letra 'S' está formada por la silueta de un cable con sus conectores, representando de manera directa y conceptual la actividad de la empresa. Este símbolo se acompaña de una tipografía fina y geométrica que refuerza el carácter tecnológico y moderno de la marca, logrando una identidad limpia y alineada con su sector.",
    gallery: [
      {
      src: "/images/portfolio/siami/sia-01.jpg",
        width: 1556,
        height: 992,
        hint: "logo",
      },
      {
      src: "/images/portfolio/siami/sia-02.jpg",
        width: 1556,
        height: 992,
        hint: "negative logo close-up",
      },
    ],
  },
  {
    id: "xv-valencia-fashion-week",
    title: "XV Valencia Fashion Week",
    subtitle: "Branding",
    categories: ["Logo", "Branding"],
    year: "2014",
    mainImage: {
      src: "/images/portfolio/valencia-fashion-week/vfw-00.jpg",
      width: 1333,
      height: 1333,
      hint: "poster mockup",
    },
    description: "Identidad gráfica y comunicación visual desarrollada para la XV edición de la Valencia Fashion Week, junto con NIL Comunicación, bajo el lema #descaradamentjóvenes. El concepto se materializa en una  estética vibrante, fresca y enérgica, que emplea una paleta de colores llamativa. La identidad se aplicó de forma integral a la gran variedad de soportes que un evento de esta magnitud requiere, incluyendo cartelería, programas de actividades, invitaciones, y múltiples tipos de acreditaciones (prensa, backstage), asegurando una experiencia visual coherente y llena de energía.",
    gallery: [
      {
      src: "/images/portfolio/valencia-fashion-week/vfw-01.jpg",
        width: 1556,
        height: 992,
        hint: "billboard mockup",
      },
      {
      src: "/images/portfolio/valencia-fashion-week/vfw-02.jpg",
        width: 1556,
        height: 992,
        hint: "stationery mockup",
      },
      {
      src: "/images/portfolio/valencia-fashion-week/vfw-03.jpg",
        width: 1556,
        height: 992,
        hint: "flyer close-up",
      },
      {
      src: "/images/portfolio/valencia-fashion-week/vfw-04.jpg",
        width: 1556,
        height: 992,
        hint: "wall vinlys",
      },
      {
      src: "/images/portfolio/valencia-fashion-week/vfw-05.jpg",
        width: 1556,
        height: 992,
        hint: "wall vinyls and flyers",
      },
      {
      src: "/images/portfolio/valencia-fashion-week/vfw-06.jpg",
        width: 1556,
        height: 992,
        hint: "wall vinlys and outside sign",
      },
    ],
  },
  {
    id: "moddos",
    title: "Moddos Club",
    subtitle: "Diseño Gráfico",
    categories: ["Diseño Gráfico", "Editorial"],
    year: "2014",
    mainImage: {
      src: "/images/portfolio/moddos/mod-00.jpg",
      width: 1333,
      height: 1333,
      hint: "poster mockup",
    },
    description: "Durante mi etapa en 'Moddos', un club de empresas, desempeñé un rol de diseñador encargado de la comunicación visual tanto para la organización principal como para sus diversas compañías asociadas. Mi labor principal se centró en el diseño y la maquetación de las revistas online del club, creando contenido editorial digital para fomentar la conexión entre los miembros. Además, desarrollé una amplia variedad de material corporativo, no solo para el club, sino también para las empresas que lo conformaban, adaptándome a sus distintas identidades de marca y necesidades de comunicación. Esta experiencia me permitió trabajar en un entorno dinámico y gestionar múltiples proyectos y estilos de forma simultánea.",
    gallery: [
      {
      src: "/images/portfolio/moddos/mod-01.jpg",
        width: 1556,
        height: 992,
        hint: "billboard mockup",
      },
      {
      src: "/images/portfolio/moddos/mod-02.jpg",
        width: 1556,
        height: 992,
        hint: "stationery mockup",
      },
      {
      src: "/images/portfolio/moddos/mod-03.jpg",
        width: 1556,
        height: 992,
        hint: "flyer close-up",
      },
      {
      src: "/images/portfolio/moddos/mod-04.jpg",
        width: 1556,
        height: 992,
        hint: "wall vinlys",
      },
      {
      src: "/images/portfolio/moddos/mod-05.jpg",
        width: 1556,
        height: 992,
        hint: "wall vinyls and flyers",
      },
    ],
  },
  {
    id: "imz",
    title: "Instituto Médico Zahrawi",
    subtitle: "Branding",
    categories: ["Logo", "Branding"],
    year: "2014",
    mainImage: {
      src: "/images/portfolio/imz/imz-00.jpg",
      width: 1333,
      height: 1333,
      hint: "logo",
    },
    description: "Desarrollo de identidad corporativa completa para el 'Instituto Médico Zahrawi'. El diseño busca proyectar profesionalismo, confianza y cuidado, utilizando un logotipo que combina una tipografía serif con un símbolo de dos arcos verdes que evocan la forma de un ojo, sugiriendo visión, precisión y bienestar. La identidad visual, que incluye una versión compacta del monograma 'IMZ', se aplica de manera consistente a través de un amplio abanico de piezas, desde la papelería corporativa hasta material publicitario y aplicaciones digitales, asegurando una imagen de marca sólida, coherente y fácilmente reconocible.",
    gallery: [
      {
      src: "/images/portfolio/imz/imz-01.jpg",
        width: 1556,
        height: 992,
        hint: "business card mockup",
      },
      {
      src: "/images/portfolio/imz/imz-02.jpg",
        width: 1556,
        height: 992,
        hint: "stationery mockup",
      },
      {
      src: "/images/portfolio/imz/imz-03.jpg",
        width: 1556,
        height: 992,
        hint: "poster mockup",
      },
      {
      src: "/images/portfolio/imz/imz-04.jpg",
        width: 1556,
        height: 992,
        hint: "logo 3d mockup on wood wall",
      },
    ],
  },
  {
    id: "gold-k",
    title: "Gold K",
    subtitle: "Logo & Packaging",
    categories: ["Logo", "Packaging"],
    year: "2013",
    mainImage: {
      src: "/images/portfolio/gold-k/gol-00.jpg",
      width: 1556,
      height: 992,
      hint: "brand marquee on wood wall",
    },
    description: "Branding y packaging para Gold K, cava de alta gama con de virutas de oro de 24 quilates en su interior. El diseño está enfocado en comunicar lujo, exclusividad y calidad premium, utilizando una paleta de colores elegante de negro y dorado, y un logotipo que incorpora una corona como símbolo de estatus. Se presentan dos variantes del producto, 'Reserva Especial' y 'Premium', diferenciadas por el color de la cápsula (dorada y negra, respectivamente), pero unificadas bajo una misma identidad visual sofisticada que resalta el carácter opulento de la bebida.",
    gallery: [
      {
      src: "/images/portfolio/gold-k/gol-01.jpg",
        width: 1556,
        height: 992,
        hint: "logo construction angles",
      },
      {
      src: "/images/portfolio/gold-k/gol-02.jpg",
        width: 1556,
        height: 992,
        hint: "brand icons",
      },
      {
      src: "/images/portfolio/gold-k/gol-03.jpg",
        width: 1556,
        height: 992,
        hint: "brand marquee",
      },
      {
      src: "/images/portfolio/gold-k/gol-04.jpg",
        width: 1556,
        height: 992,
        hint: "business card mockup",
      },
      {
      src: "/images/portfolio/gold-k/gol-05.jpg",
        width: 1556,
        height: 992,
        hint: "brand pattern poster mockup",
      },
      {
      src: "/images/portfolio/gold-k/gol-06.jpg",
        width: 1556,
        height: 992,
        hint: "brand pattern poster mockup",
      },
      {
      src: "/images/portfolio/gold-k/gol-07.jpg",
        width: 1556,
        height: 992,
        hint: "brand pattern poster mockup",
      },
      {
      src: "/images/portfolio/gold-k/gol-08.jpg",
        width: 1556,
        height: 992,
        hint: "brand pattern poster mockup",
      },
    ],
  },
  {
    id: "bangarang",
    title: "Bangarang",
    subtitle: "Branding",
    categories: ["Logo", "Branding"],
    year: "2013",
    mainImage: {
      src: "/images/portfolio/bangarang/ban-00.jpg",
      width: 1556,
      height: 992,
      hint: "brand marquee on wood wall",
    },
    description: "Para Bangarang se desarrolló un proyecto integral de branding y diseño de identidad visual. El proceso cubrió desde la creación del logotipo hasta su aplicación en papelería (tarjetas, flyers) y en elementos físicos del local, como vinilos y el toldo principal, logrando una imagen de marca coherente y unificada.",
    gallery: [
      {
      src: "/images/portfolio/bangarang/ban-01.jpg",
        width: 1556,
        height: 992,
        hint: "logo construction angles",
      },
      {
      src: "/images/portfolio/bangarang/ban-02.jpg",
        width: 1556,
        height: 992,
        hint: "brand icons",
      },
      {
      src: "/images/portfolio/bangarang/ban-03.jpg",
        width: 1556,
        height: 992,
        hint: "brand marquee",
      },
      {
      src: "/images/portfolio/bangarang/ban-04.jpg",
        width: 1556,
        height: 992,
        hint: "business card mockup",
      },
      {
      src: "/images/portfolio/bangarang/ban-05.jpg",
        width: 1556,
        height: 992,
        hint: "brand pattern poster mockup",
      },
    ],
  },
  {
    id: "fanaticos",
    title: "Fanáticos",
    subtitle: "Packaging",
    categories: ["Packaging"],
    year: "2012",
    mainImage: {
      src: "/images/portfolio/fanaticos/fan-00.jpg",
      width: 1556,
      height: 992,
      hint: "CD case cover mockup",
    },
    description: "Diseño gráfico para el álbum 'Bichos Raros' de la banda Fanáticos. El concepto visual interpreta el título del disco mediante la creación de figuras simétricas y lineales que asemejan insectos o criaturas abstractas. La estética se define por un minimalismo técnico, utilizando un fondo negro sobre el que destacan ilustraciones con un efecto estereoscópico o anaglifo (líneas rojas y cian). Este lenguaje de diseño se aplica de forma coherente a todas las piezas del álbum: la portada, el libreto interior con créditos y letras, y la galleta del CD, conformando una identidad visual coherente y distintiva.",
    gallery: [
      {
      src: "/images/portfolio/fanaticos/fan-01.jpg",
        width: 1556,
        height: 992,
        hint: "cover and CD mockup",
      },
      {
      src: "/images/portfolio/fanaticos/fan-02.jpg",
        width: 1556,
        height: 992,
        hint: "CD and booklet mockup",
      },
      {
      src: "/images/portfolio/fanaticos/fan-03.jpg",
        width: 1556,
        height: 992,
        hint: "booklet mockup",
      },
      {
      src: "/images/portfolio/fanaticos/fan-04.jpg",
        width: 1556,
        height: 992,
        hint: "cover design",
      },
      {
      src: "/images/portfolio/fanaticos/fan-05.jpg",
        width: 1556,
        height: 992,
        hint: "cover artwork",
      },
    ],
  },
  {
    id: "hannah",
    title: "Hannah",
    subtitle: "Logo",
    categories: ["Logo"],
    year: "2012",
    mainImage: {
      src: "/images/portfolio/hannah/han-00.jpg",
      width: 1556,
      height: 992,
      hint: "logo color animated gif",
    },
    description: "Diseño de logotipo para marca personal. El elemento central es un monograma que fusiona las letras 'H' y 'N' dentro de un círculo, utilizando un estilo de línea fina y geométrica para crear un símbolo moderno y equilibrado. Este enfoque lineal se refleja en la tipografía personalizada del nombre, aportando coherencia visual. La paleta de colores, que combina el blanco y negro con un acento de verde menta, aporta un toque de frescura, resultando en una identidad visual limpia, personal y versátil, adaptable a formatos animados para uso digital.",
    gallery: [
      {
      src: "/images/portfolio/hannah/han-01.gif",
        width: 1556,
        height: 992,
        hint: "logo",
      },
    ],
  },
  {
    id: "el-metodo-havana-7",
    title: "El Método Havana 7",
    subtitle: "Campaña Publicitaria",
    categories: ["Logo", "Publicitario"],
    year: "2011",
    mainImage: {
      src: "/images/portfolio/el-metodo-havana-7/elm-00.jpg",
      width: 1556,
      height: 992,
      hint: "logo perspective on dark background",
    },
    description: "Branding y campaña de publicidad para el ron Havana Club 7 Años bajo el concepto 'El Método Havana', utilizando una paleta de colores oscuros, rojos y dorados para evocar calidad y exclusividad. Las piezas gráficas incluyen un logotipo, un cartel y tarjetas promocionales.",
    gallery: [
      {
      src: "/images/portfolio/el-metodo-havana-7/elm-01.jpg",
        width: 1556,
        height: 992,
        hint: "poster mockup",
      },
      {
      src: "/images/portfolio/el-metodo-havana-7/elm-02.jpg",
        width: 1556,
        height: 992,
        hint: "flyer mockup",
      },
      {
      src: "/images/portfolio/el-metodo-havana-7/elm-03.jpg",
        width: 1556,
        height: 992,
        hint: "flyer mockup",
      },
    ],
  },
  {
    id: "granja-vectorial",
    title: "Granja Vectorial",
    subtitle: "Ilustraciones Digitales",
    categories: ["Ilustración"],
    year: "2010",
    mainImage: {
      src: "/images/portfolio/granja-vectorial/gra-01.jpg",
      width: 1556,
      height: 992,
      hint: "bird illustration",
    },
    description: "Este proyecto es una serie de ilustraciones digitales que presentan un bestiario de criaturas estilizadas con un lenguaje visual común. El estilo gráfico se basa en la técnica 'low-poly', construyendo los personajes (tortugas, una serpiente, un insecto) a partir de formas geométricas y polígonos de colores planos y vibrantes. Esta estética vectorial y facetada, combinada con fondos de colores intensos y degradados, crea un universo visual donde cada ilustración explora el diseño de personajes con una identidad gráfica distintiva y minimalista.",
    gallery: [
      {
      src: "/images/portfolio/granja-vectorial/gra-02.jpg",
        width: 1556,
        height: 992,
        hint: "turtles illustration",
      },
      {
      src: "/images/portfolio/granja-vectorial/gra-03.jpg",
        width: 1556,
        height: 992,
        hint: "snake illustration",
      },
      {
      src: "/images/portfolio/granja-vectorial/gra-04.jpg",
        width: 1556,
        height: 992,
        hint: "fly illustration",
      },
      {
      src: "/images/portfolio/granja-vectorial/gra-05.jpg",
        width: 1556,
        height: 992,
        hint: "crocodile illustration",
      },
      {
      src: "/images/portfolio/granja-vectorial/gra-06.jpg",
        width: 1556,
        height: 992,
        hint: "dog illustration",
      },
      {
      src: "/images/portfolio/granja-vectorial/gra-07.jpg",
        width: 1556,
        height: 992,
        hint: "monkey illustration",
      },
      {
      src: "/images/portfolio/granja-vectorial/gra-08.jpg",
        width: 1556,
        height: 992,
        hint: "koala illustration",
      },
      {
      src: "/images/portfolio/granja-vectorial/gra-09.jpg",
        width: 1556,
        height: 992,
        hint: "pig illustration",
      },
      {
      src: "/images/portfolio/granja-vectorial/gra-10.jpg",
        width: 1556,
        height: 992,
        hint: "frog illustration",
      },
    ],
  },
  {
    id: "galeria9",
    title: "galería9",
    subtitle: "Dirección de Arte",
    categories: ["Editorial", "Publicitario"],
    year: "2008",
    mainImage: {
      src: "/images/portfolio/galeria9/gal-00.jpg",
      width: 1556,
      height: 992,
      hint: "logo perspective on dark background",
    },
    description: "Durante mi larga trayectoria en galería9, desempeñé un rol integral como el diseñador principal, encargado de toda la comunicación visual y la estrategia digital de la galería. Mis responsabilidades abarcaban desde el concepto hasta la ejecución de cada aspecto de la presencia de la marca. Para cada exposición, gestionaba el ciclo completo de comunicación: desde el diseño de la cartelería y los flyers, hasta la fotografía de las obras de arte y la actualización del contenido en la página web. Además, lideré proyectos estratégicos clave para la modernización de la galería, como la digitalización completa de su fondo artístico para su preservación y la creación desde cero de su tienda online. Finalmente, también me encargaba de la planificación y el diseño de las campañas de publicidad. Este rol multifacético me permitió no solo definir la identidad visual de la galería, sino también impulsar su transición al espacio digital y comercial.",
    gallery: [
      {
      src: "/images/portfolio/galeria9/gal-01.jpg",
        width: 1556,
        height: 992,
        hint: "poster mockup",
      },
      {
      src: "/images/portfolio/galeria9/gal-02.jpg",
        width: 1556,
        height: 992,
        hint: "flyer mockup",
      },
    ],
  },];
